# __Function examination__

References:
- https://numpy.org/doc/stable/reference/generated/numpy.pad.html
- https://stackoverflow.com/questions/11295609/

In [1]:
import numpy as np
import pandas as pd
from glob import glob

## 1-d array

In [2]:
a = [1, 2, 3, 4, 5]

In [4]:
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [3]:
np.pad(a, (2, 3), 'edge')

array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [7]:
np.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4))

array([ 5,  3,  1,  2,  3,  4,  5,  2, -1, -4])

In [6]:
np.pad(a, (2,), 'maximum')

array([5, 5, 1, 2, 3, 4, 5, 5, 5])

In [8]:
np.pad(a, (2,), 'mean')

array([3, 3, 1, 2, 3, 4, 5, 3, 3])

In [9]:
np.pad(a, (2,), 'median')

array([3, 3, 1, 2, 3, 4, 5, 3, 3])

In [11]:
np.pad(a, (2, 10), 'reflect')

array([3, 2, 1, 2, 3, 4, 5, 4, 3, 2, 1, 2, 3, 4, 5, 4, 3])

In [13]:
np.pad(a, (2, 10), 'reflect', reflect_type='odd')

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
np.pad(a, (2, 3), 'symmetric')

array([2, 1, 1, 2, 3, 4, 5, 5, 4, 3])

In [17]:
np.pad(a, (2, 11), 'symmetric', reflect_type='odd')

array([ 0,  1,  1,  2,  3,  4,  5,  5,  6,  7,  8,  9,  9, 10, 11, 12, 13,
       13])

In [18]:
np.pad(a, (2, 3), 'wrap')

array([4, 5, 1, 2, 3, 4, 5, 1, 2, 3])

## 2-d array

In [76]:
a = [[1, 2], [3, 4]]

In [73]:
a

[[1, 2], [3, 4]]

In [104]:
hoge = np.pad(a, ((2, 0), (1, 0)), 'constant', constant_values=0)

In [105]:
hoge

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [106]:
w, h = hoge.shape

In [107]:
w

4

In [38]:
type(hoge)

numpy.ndarray

In [45]:
foo = np.array(list())

In [49]:
foo.size

0

In [50]:
bar = np.array(None)

In [51]:
bar.size

1

In [56]:
hage = bool(bar.shape and bar.size)

In [57]:
hage

False

In [95]:
(5 - 4) % 2 

1

In [96]:
5 % 2 == 0

False

In [103]:
int (3/2)

1

## Function example

In [59]:
def has_element(np_array: np.ndarray) -> bool:
    return bool(np_array.ndim and np_array.size)

In [70]:
def get_min_from_array(np_array: np.ndarray) -> float:
    return np_array.flatten().min()

In [97]:
def is_even(num: int) -> bool:
    return num % 2 == 0

In [121]:
def pad_spectrogram(np_array: np.ndarray, target_size_w: int = 0, target_size_h: int = 0,
                    pad_value: int = -1) -> np.ndarray:
    # for safety
    if not has_element(np_array):
        return np.ndarray(list())
    
    # flags
    do_horizontal_padding = False
    do_vertical_padding = False
    pad_size_left = pad_size_right = pad_size_top = 0

    # obtain & calculate information
    arr_height, arr_width = np_array.shape

    # calculate padding size
    if arr_width < target_size_w:
        do_horizontal_padding = True
        pad_size_left = int((target_size_w - arr_width) / 2)
        pad_size_right = int((target_size_w - arr_width) / 2) \
            if is_even(target_size_w - arr_width) \
            else int((target_size_w - arr_width) / 2) + 1
    
    if arr_height < target_size_h:
        do_vertical_padding = True
        pad_size_top = target_size_h - arr_height

    # Confirm necessity to execute padding
    if not (do_horizontal_padding or do_vertical_padding):
        return np_array

    # define value to pad a spectrogram
    pad_value = pad_value if pad_value >= 0 else get_min_from_array(np_array)

    # Pad the array horizontally here
    np_array_pad = np.pad(np_array, ((pad_size_top, 0), (pad_size_left, pad_size_right)),
                          'constant', constant_values=pad_value)

    # Pad the array vertically here
    return np_array_pad

In [122]:
a = np.arange(6)
a = a.reshape((2, 3))

In [123]:
a.shape

(2, 3)

In [126]:
pad_spectrogram(np_array=a, target_size_w=5, target_size_h=3, pad_value=100)

array([[100, 100, 100, 100, 100],
       [100,   0,   1,   2, 100],
       [100,   3,   4,   5, 100]])

In [24]:
np.pad(a, 2, pad_with)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10,  0,  1,  2, 10, 10],
       [10, 10,  3,  4,  5, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [32]:
np.pad(a, 2, pad_with_a)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10,  0,  1,  2,  0,  0],
       [10, 10,  3,  4,  5,  0,  0],
       [10, 10,  0,  0,  0,  0,  0],
       [10, 10,  0,  0,  0,  0,  0]])

In [25]:
np.pad(a, 3, pad_with, padder=100)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100,   0,   1,   2, 100, 100, 100],
       [100, 100, 100,   3,   4,   5, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [27]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [29]:
a

array([[0, 1, 2],
       [3, 4, 5]])